FROM postgres:latest
ENV POSTGRES_USER=appadminuser
ENV POSTGRES_PASSWORD=supersecurepass

COPY ./init.sql /docker-entrypoint-initdb.d/
VOLUME /var/lib/postgresql/data

EXPOSE 5432
CMD ["postgres", "-c", "listen_addresses=*"]

